# Generated by Django 5.0.7 on 2024-10-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('english_name', models.CharField(max_length=100)),
                ('is_planet', models.BooleanField(default=True)),
                ('semimajor_axis', models.BigIntegerField()),
                ('perihelion', models.BigIntegerField()),
                ('aphelion', models.BigIntegerField()),
                ('eccentricity', models.FloatField()),
                ('inclination', models.FloatField()),
                ('mass_value', models.FloatField()),
                ('mass_exponent', models.IntegerField()),
                ('vol_value', models.FloatField()),
                ('vol_exponent', models.IntegerField()),
                ('density', models.FloatField()),
                ('gravity', models.FloatField()),
                ('escape_velocity', models.IntegerField()),
                ('mean_radius', models.FloatField()),
                ('equatorial_radius', models.FloatField()),
                ('polar_radius', models.FloatField()),
                ('flattening', models.FloatField()),
                ('sideral_orbit', models.FloatField()),
                ('sideral_rotation', models.FloatField()),
                ('axial_tilt', models.FloatField()),
                ('average_temperature', models.IntegerField()),
                ('main_anomaly', models.FloatField()),
                ('arg_periapsis', models.FloatField()),
                ('long_asc_node', models.FloatField()),
                ('body_type', models.CharField(default='Planet', max_length=50)),
                ('moons', models.ManyToManyField(blank=True, to='solar_system_api.moon')),
            ],
        ),
    ]
