# Generated by Django 5.0.7 on 2024-10-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='x',
            field=models.IntegerField(default=1, verbose_name='Высота'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planet',
            name='y',
            field=models.IntegerField(default=1, verbose_name='Длина'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planet',
            name='z',
            field=models.IntegerField(default=1, verbose_name='Ширина'),
            preserve_default=False,
        ),
    ]
